### ISSUE TITLE
Clarification needed for order in the same thread.

### ISSUE THREAD

**Issue by Daniel-Xu** [m-ou-se/rust-atomics-and-locks#1]
First of all, Thanks for the great book.
Secondly, if this is not the right place to talk about the book, let me know. 

From the Chapter 3:

![2023-01-06 at 1 29 PM](https://user-images.githubusercontent.com/548144/210936535-3d728ed3-aad2-4292-b587-4cdb47c5c277.png)

AFAIK, `compiler reorder`, `runtime instruction reorder` and `store buffer` can all change the order of the 
of the execution. 
Not sure how to digest the statement in the picture above, and it's so hard to reason about the `0 20` example by following it ↑.

**Comment by m-ou-se** [comment]
> AFAIK, `compiler reorder`, `runtime instruction reorder` and `store buffer` can all change the order of the of the execution.

That is true, but none of those things are visible within the same thread. Everything within the same thread still appears to happen in order. The abstract "happens-before" relationship model isn't about the order in which operations happen physically in the processor (for that, see chapter 7). It defines the order in which operations can observed from within your program.

The `0 20` example can happen because there are no happens-before relationship between the threads. Within thread 1, you'll always see (1) happen before (2), regardless of reordering. Reordering is only visible from another thread.

**Comment by Daniel-Xu** [comment]
For anyone who has the same confusion, make sure to read this: 
https://preshing.com/20130702/the-happens-before-relation/
