### ISSUE TITLE
More explanation needed on why use SeqCst in Chapter 3

### ISSUE THREAD

**Issue by KaneGreen** [m-ou-se/rust-atomics-and-locks#17]
### The content that the question is about

In [section 'Sequentially Consistent Ordering'](https://marabos.nl/atomics/memory-ordering.html#seqcst) of the Chapter 3, it says the example 'depends on sequentially consistent ordered operations'.

### The question

However, I tried use the happen-before relationship to analyze: what if I use 'Release-store' and 'Acquire-load' instead of `SeqCst`. But I cannot find any problems and I thought it would work well even if no `SeqCst`. The fact is not.

I cannot figure out why using the happen-before relationship.

--------------
Appendix:
I use a slightly modified code as following:
```rust
use std::sync::atomic::{AtomicBool, Ordering};
use std::thread;

static A: AtomicBool = AtomicBool::new(false);
static B: AtomicBool = AtomicBool::new(false);
static mut AS: isize = 0;
static mut BS: isize = 0;

fn main() {
    let a = thread::spawn(|| {
        A.store(true, Ordering::Release);
        if !B.load(Ordering::Acquire) {
            unsafe { AS += 1 };
        }
    });
    let b = thread::spawn(|| {
        B.store(true, Ordering::Release);
        if !A.load(Ordering::Acquire) {
            unsafe { BS += 1 };
        }
    });
    a.join().unwrap();
    b.join().unwrap();
    unsafe {
        println!("{} {}", AS, BS);
    }
}
```
In a large number of runs, there is a small probability of "1 1" outputs, which means both `B.load()` and `A.load()` return `false`.
So, the `SeqCst` is needed.

But why?

**Comment by m-ou-se** [comment]
In the runs where you got a "1 1" output, the first thread performed these two operations:

1. release-store true to A,
2. acquire-load false from B,

and the second thread performed these two operations:

3. release-store true to B,
4. acquire-load false from A.

There is a happens-before relationship between 1 and 2 (because they are part of the same thread), and between 3 and 4 (for the same reason). But there is no happens-before relationship between the threads, in this case.

*If* 4 had loaded `true`, *then* there would have been a happens-before relationship between 1 (which stored that `true`) and 4 (which loaded that `true`). That's how inter-thread happens-before relationships are created. But there is no guarantee that 4 will load `true`.

(See the first example and figure in https://marabos.nl/atomics/memory-ordering.html#release-and-acquire-ordering: there is no guarantee when the main thread will observe `READY` to be `true`, and a happens-before relationship is only formed when it does load the (release-stored) `true`.)

With SeqCst it's different, because there is no possible global order (1234, 1324, 1342, 3412, 3142, 3124) that would result in both loads seeing `false`.

**Comment by KaneGreen** [comment]
Is it the following thinking that caused my mistake:
> if 4 had loaded `false`, then 1 must haven't happened. Thus, 4 happens-before 1, and we already know 1 happens-before 2 and 3 happens before 4, --> so we get `B` must acquire-load the release-stored `true`

But in fact, only if 4 had loaded `true`, can we say 1 happens-before 4. If 4 had loaded `false`, we can say nothing and in 2 `B` can load either `true` or `false`. Is this right?

**Comment by m-ou-se** [comment]
Indeed.

> > if 4 had loaded `false`, then 1 must haven't happened. Thus, 4 happens-before 1, [..]

Such "hasn't-happened-before" kind of reasoning only works if you assume there is a single global order (which only SeqCst gives you).

> If 4 had loaded `false`, we can say nothing and in 2 `B` can load either `true` or `false`. Is this right?

Correct!

**Comment by KaneGreen** [comment]
That makes sense. Thank you a lot.

I'll close this issue.
