### ISSUE TITLE
will fetch_add with relaxed ordering cause update loss?

### ISSUE THREAD

**Issue by Daniel-Xu** [m-ou-se/rust-atomics-and-locks#2]
![2023-01-14 at 11 36 PM](https://user-images.githubusercontent.com/548144/212480100-ec1638f0-85e5-4050-8fb5-97d1d3eccf8d.png)

Given the code above, the `fetch_add` is used with relaxed ordering:
I thought the update in one thread might not be visible in another thread, therefore the result might be less than 100. 
This has no issue in X86 as it has a strong memory model by default. 

Am I missing anything or misunderstanding the ordering concept?

**Comment by m-ou-se** [comment]
It's not really a matter of _if_ the other threads will see the update, but more about _when_. More specifically, whether they observe the update before or after the result of some other operation. The main thread might see the counter reach 100 some nanoseconds too early or too late, so you can't have (unsafe) code assume that everything that `process_item()` did is visible as soon as it observes the counter reaching 100. But for progress reporting to the user, or knowing when to join the threads, this is fine.

Stronger memory ordering doesn't change anything about that by the way. The memory model doesn't say anything about when or if updates are visible on other threads. It only specifies in which order things are observable. See the first myth listed here: https://marabos.nl/atomics/memory-ordering.html#common-misconceptions

Also note that after the scope() function returns, we _can_ make the assumption that everything the threads did is observable (including whatever `process_item()` did), because joining a thread comes with ordering guarantees, as described here: https://marabos.nl/atomics/memory-ordering.html#spawning-and-joining

Hope that helps!

**Comment by Daniel-Xu** [comment]
Thanks for the reply, the reason why I asked is because of this example:

![2023-01-15 at 12 53 AM](https://user-images.githubusercontent.com/548144/212485128-037f6509-6959-4d47-82fc-42b507472947.png)

It's from Jon's video: https://www.youtube.com/watch?v=rMGWeSjctlY
## Conclusion
It's possible for z to be 0. 

## Reason
In t1, when `x` is `true`, there's no synchronization between `x` and `y`, so we can still see y as `false`
It's the same for x in `t2`

That's why we can get 0 for z in the end. 

## Analogy
To apply the same logic to the `fetch_add` example, let me simplify the code (in c++):
```
std::atomic<int> a(0);

void thread1()
{
    int x = a.fetch_add(1, std::memory_order_relaxed);
    std::cout << x << std::endl;
}

void thread2()
{
    int x = a.fetch_add(1, std::memory_order_relaxed);
    std::cout << x << std::endl;
}

int main()
{
    std::thread t1(thread1);
    std::thread t2(thread2);

    t1.join();
    t2.join();
    // a will be 2
    return 0; 
}

```
the conclusion is: `a will be 2 in the end`


## my confusion

In my imaginary implementation of `fetch_add`:

```
v = load(x)
store(x, v+1)
// somehow those two are grouped together (for the atomicity)
```
if there are no synchronizations among different threads, the `v` might all be 0, and 1 should be possible for the final result of `a`.  (I knew this is impossible, it just contradicts the first example I gave, so I'm kinda lost)

**Comment by m-ou-se** [comment]
That's not possible because of the _total modification order_ of `a`. See https://marabos.nl/atomics/memory-ordering.html#relaxed

**Comment by Daniel-Xu** [comment]
👍  atomic RMW (read-modify-write) guarantees the total modification order.

**Comment by jonhoo** [comment]
It's been a while since that video, but I believe it is true that `z` can be 0 in that particular program that's been screenshotted. However, it's not because an update to `z` is "lost", it's because it's legal for the processor to make it so that both threads that _update_ `z` see a sequence of events such that their individual `if` conditions both evaluate to false. If memory serves me right (😅), that particular example was taken from the C++ std concurrency documentation and adapted to Rust. It does *not* apply to the modified "analogy" code posted above though, as that joins the threads and doesn't use relaxed + acq/rel semantics, nor the number of threads required to reproduce the particularly weird behavior.

**Comment by Daniel-Xu** [comment]
The only way to guarantee you have the "latest" value is to use a read-modify-write operation such as exchange(), compare_exchange_strong() or fetch_add(). Read-modify-write operations have an additional constraint that they always operate on the "latest" value, so a sequence of ai.fetch_add(1) operations by a series of threads will return a sequence of values with no duplicates or gaps. In the absence of additional constraints, there's still no guarantee which threads will see which values though. In particular, it is important to note that the use of an RMW operation does not force changes from other threads to become visible any quicker, it just means that if the changes are not seen by the RMW then all threads must agree that they are later in the modification order of that atomic variable than the RMW operation. Stores from different threads can still be delayed by arbitrary amounts of time, depending on when the CPU actually issues the store to memory (rather than just its own store buffer), physically how far apart the CPUs executing the threads are (in the case of a multi-processor system), and the details of the cache coherency protocol.

-- from the Author of <C++ concurrency in action> 
 
https://stackoverflow.com/questions/8819095/concurrency-atomic-and-volatile-in-c11-memory-model/8833218#8833218

This solves the confusion I had.
